export const endpoints = {
  health: '/health',
  incidents: '/incidents',
  incidentById: (id: number) => `/incidents/${id}`,
  incidentReplay: (id: number) => `/incidents/${id}/replay`,
  incidentSimilar: (id: number) => `/incidents/${id}/similar`,
  services: '/incidents/services',
  metrics: '/metrics',
  exceptionMetrics: '/metrics/exceptions',
  serviceMetrics: '/metrics/services',
  analysis: {
    dashboard: '/analysis/dashboard',
    executiveSummary: '/analysis/executive-summary',
    liveDashboard: '/analysis/live-dashboard',
    dashboardSnapshot: '/analysis/dashboard-snapshot',
    hourlyTrend: '/analysis/hourly-trend',
    trendSummary: '/analysis/trend-summary',
    spikeDetection: '/analysis/spike-detection',
    severity: '/analysis/severity',
    liveCount: '/analysis/live-count',
    liveServices: '/analysis/live-services',
    liveExceptions: '/analysis/live-exceptions',
    recentIncidents: '/analysis/recent-incidents',
    scoredAlerts: '/analysis/scored-alerts',
    serviceRanking: '/analysis/service-ranking',
    exceptionRanking: '/analysis/exception-ranking',
    correlations: '/analysis/correlations',
    recentCorrelations: '/analysis/recent-correlations',
    rcaSummary: '/analysis/rca-summary',
    recentRcaSummary: '/analysis/recent-rca-summary',
    recommendations: '/analysis/recommendations',
    recommendationSummary: '/analysis/recommendation-summary',
    serviceDependencies: '/analysis/service-dependencies',
    topDependencies: '/analysis/top-dependencies',
    dependencySummary: '/analysis/dependency-summary',
    dependencyRisks: '/analysis/dependency-risks',
    cascadeFailures: '/analysis/cascade-failures',
    dependencyExecutiveSummary: '/analysis/dependency-executive-summary',
    dependencyImpacts: '/analysis/dependency-impacts',
    dependencyImpactSummary: '/analysis/dependency-impact-summary',
    dependencyImpactExecutiveSummary: '/analysis/dependency-impact-executive-summary',
    dependencyRiskScores: '/analysis/dependency-risk-scores',
    dependencyRiskDashboard: '/analysis/dependency-risk-dashboard',
    failurePredictions: '/analysis/failure-predictions',
    predictionSummary: '/analysis/prediction-summary',
    predictionExecutiveSummary: '/analysis/prediction-executive-summary',
    anomalies: '/analysis/anomalies',
    anomalySummary: '/analysis/anomaly-summary',
    anomalyExecutiveSummary: '/analysis/anomaly-executive-summary',
    knowledgeGraph: '/analysis/knowledge-graph',
    knowledgeGraphSummary: '/analysis/knowledge-graph-summary',
    knowledgeGraphExecutiveSummary: '/analysis/knowledge-graph-executive-summary',
    serviceReliability: '/analysis/service-reliability',
    reliabilitySummary: '/analysis/reliability-summary',
    reliabilityExecutiveSummary: '/analysis/reliability-executive-summary',
    reliabilityTimeline: (serviceName?: string, period = '7d') =>
      `/analysis/reliability-timeline?period=${period}${serviceName ? `&serviceName=${encodeURIComponent(serviceName)}` : ''}`,
    autonomousActions: '/analysis/autonomous-actions',
    actionSummary: '/analysis/action-summary',
    actionExecutiveSummary: '/analysis/action-executive-summary',
    selfHealingRecommendations: '/analysis/self-healing-recommendations',
    selfHealingSummary: '/analysis/self-healing-summary',
    selfHealingExecutiveSummary: '/analysis/self-healing-executive-summary',
    selfHealingDashboard: '/analysis/self-healing-dashboard',
    automationReadiness: '/analysis/automation-readiness',
    automationReadinessSummary: '/analysis/automation-readiness-summary',
    automationReadinessExecutiveSummary: '/analysis/automation-readiness-executive-summary',
    automationReadinessDashboard: '/analysis/automation-readiness-dashboard',
    autonomousExecutionPlans: '/analysis/autonomous-execution-plans',
    orchestratorSummary: '/analysis/orchestrator-summary',
    orchestratorExecutiveSummary: '/analysis/orchestrator-executive-summary',
    orchestratorDashboard: '/analysis/orchestrator-dashboard',
    operationalPriorities: '/analysis/operational-priorities',
    aiopsSummary: '/analysis/aiops-summary',
    aiopsExecutiveSummary: '/analysis/aiops-executive-summary',
    aiopsDashboard: '/analysis/aiops-dashboard',
    serviceResilience: '/analysis/service-resilience',
    serviceResilienceSummary: '/analysis/service-resilience-summary',
    serviceResilienceExecutiveSummary: '/analysis/service-resilience-executive-summary',
    resilienceRecommendations: '/analysis/resilience-recommendations',
    resilienceDashboard: '/analysis/resilience-dashboard',
  },
  auth: {
    login: '/api/auth/login',
    session: '/api/auth/session',
  },
  search: '/api/search',
  auditLogs: '/api/audit-logs',
  alertSubscriptions: '/api/alert-subscriptions',
  alertSubscriptionById: (id: number) => `/api/alert-subscriptions/${id}`,
  infrastructure: {
    summary: '/api/infrastructure/summary',
    hosts: '/api/infrastructure/hosts',
    services: '/api/infrastructure/services',
    dependencies: '/api/infrastructure/dependencies',
    serviceProfiles: '/api/infrastructure/service-profiles',
    serviceProfile: (name: string) => `/api/infrastructure/service-profile/${encodeURIComponent(name)}`,
  },
  changes: {
    post: '/api/changes',
    recent: '/api/changes/recent',
    correlations: (incidentId: number) => `/api/changes/correlations?incidentId=${incidentId}`,
    narrative: (incidentId: number) => `/api/changes/narrative/${incidentId}`,
    serviceNarrative: (serviceName: string) => `/api/changes/service-narrative/${encodeURIComponent(serviceName)}`,
  },
  businessServices: {
    list: '/api/business-services',
    impact: '/api/business-services/impact',
  },
  operationalBriefing: {
    today: '/api/operational-briefing/today',
    metrics: '/api/operational-briefing/metrics',
  },
  copilot: {
    ask: '/api/copilot/ask',
  },
};
